# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT dnactions.wsgi

beta_settings:
    cloud_sql_instances: carbide-oarlock-163821:us-central1:dnactions

runtime_config:
  python_version: 3
# [END runtime]
