# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_text', models.TextField()),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_slug', models.SlugField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.ManyToManyField(to='discounts.DealType'),
        ),
        migrations.AddField(
            model_name='deal',
            name='drink_type',
            field=models.ManyToManyField(to='discounts.DrinkType'),
        ),
        migrations.AddField(
            model_name='deal',
            name='food_type',
            field=models.ManyToManyField(to='discounts.FoodType'),
        ),
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Location'),
        ),
    ]
