# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.ManyToManyField(null=True, to='discounts.DealType'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='drink_type',
            field=models.ManyToManyField(null=True, to='discounts.DrinkType'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='food_type',
            field=models.ManyToManyField(null=True, to='discounts.FoodType'),
        ),
    ]
