# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20170411_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.ManyToManyField(blank=True, to='discounts.DealType'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='drink_type',
            field=models.ManyToManyField(blank=True, to='discounts.DrinkType'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='food_type',
            field=models.ManyToManyField(blank=True, to='discounts.FoodType'),
        ),
    ]
