# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('titleText', models.CharField(max_length=255)),
                ('luhn', models.TextField(blank=True, null=True)),
                ('edmonson', models.TextField(blank=True, null=True)),
                ('mainText', models.TextField(blank=True, null=True)),
                ('redirectionUrl', models.URLField()),
            ],
        ),
    ]
